name: Deploy UserPulse VM

on:
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  STORAGE_ACCOUNT_KEY: ${{ secrets.STORAGE_ACCOUNT_KEY }}
  BLOB_SAS_TOKEN: ${{ secrets.BLOB_SAS_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/CLI@v1

      - name: Run Deployment Scripts
        run: |
          chmod +x scripts/*.sh
          ./scripts/create_rg.sh
          ./scripts/create_networking.sh
          ./scripts/create_disk.sh
          ./scripts/create_vm.sh
          ./scripts/setup_prometheus_and_app.sh
